### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by July541** [July541/haskell-search-extension#1]
- Extension
  - [ ] Don't upload data file
  - [ ] Restore cabal and google file download URL
- Search function names
  - [ ] Prune description in order to display page info.
- [ ] Search function signatures
- Document
  - [ ] Manual
- Miscellaneous
  - [ ] Tech docs
  - [ ] CI/CD
  - [ ] Evaluate memory usage
